title: "Peakborad Help"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed



collections:
  tutorials:
    output: true
    icon: question.svg
    position: 1
    title:
      en: Tutorials
      de: Tutorials

  video_tutorials:
    output: true
    icon: video.svg
    position: 0
    title:
      en: Video Tutorials
      de: Video Tutorials

  data_sources:
    output: true
    icon: database.svg
    position: 2
    title:
      en: "Data sources"
      de: "Dataquellen"

  controls:
    output: true
    icon: parameters-v.svg
    position: 3
    title:
      en: "Controls"
      de: "Controls"

  misc:
    output: true
    icon: plus-c.svg
    position: 4
    title:
      en: "Misc"
      de: "Misc"

  administration:
    output: true
    icon: id-card.svg
    position: 5
    title:
      en: "Administration"
      de: "Administration"

  scripting:
    output: true
    icon: browser.svg
    position: 6
    title:
      en: "Scripting"
      de: "Scripting"

  peakboardio:
    output: true
    icon: star.svg
    position: 7
    title:
      en: "Peakboard.io"
      de: "Peakboard.io"


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - resources
  - docs
