title: "Peakboard Help"
email:  support@peakboard.com
description: "Tutorials and articles on using Peakboard."
url: "http://help.peakboard.com/"
twitter_username: pkbrd
github_username:  Peakboard
languages: ["en", "de", "cn"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: de
languageNames:
  de: Deutsch
  en: English
  cn: Chinese
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-multiple-languages-plugin
tipue_search:
  include:
    pages: true
    collections: [tutorials, video_tutorials,data_sources,dataflows,controls,misc,administration,peakboardio]

collections:
  tutorials:
    output: true
    icon: question.svg
    position: 1
    title:
      en: "Tutorials"
      de: "Tutorials"
      cn: "placeholder-Tutorials"

  video_tutorials:
    output: true
    icon: video.svg
    position: 0
    title:
      en: "Video Tutorials"
      de: "Video Tutorials"
      cn: "placeholder-Video Tutorials"

  data_sources:
    output: true
    icon: database.svg
    position: 2
    title:
      en: "Data Sources"
      de: "Datenquellen"
      cn: "placeholder-Data Sources"
      
  dataflows:
    output: true
    icon: database.svg
    position: 3
    title:
      en: "Dataflows"
      de: "Dataflows"
      cn: "placeholder-Dataflows"

  controls:
    output: true
    icon: parameters-v.svg
    position: 4
    title:
      en: "Controls"
      de: "Controls"
      cn: "placeholder-Controls"

  misc:
    output: true
    icon: plus-c.svg
    position: 5
    title:
      en: "Misc"
      de: "Misc"
      cn: "placeholder-Misc"

  administration:
    output: true
    icon: id-card.svg
    position: 6
    title:
      en: "Administration"
      de: "Administration"
      cn: "placeholder-Administration"

  scripting:
    output: true
    icon: browser.svg
    position: 7
    title:
      en: "Scripting"
      de: "Scripting"
      cn: "placeholder-Scripting"

  peakboardio:
    output: true
    icon: star.svg
    position: 8
    title:
      en: "Peakboard.io"
      de: "Peakboard.io"
      cn: "placeholder-Peakboard.io"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - resources
  - docs
